### ISSUE TITLE
Disconnecting

### ISSUE THREAD

**Issue by LEP111** [Phil0xFF/homebridge-lupus-security#5]
**Describe The Bug:**
The plugin ore the XT2 Plus keeps disconnecting every few seconds. While its disconnected you cant reach the Device
**To Reproduce:**
Install Homebridge Lupus Security paste everything in and start
**Expected behavior:**
I expected that the plugin and the XT2 Plus would stay connected 
**Question:** 
Is it because of the Plus model?
**Logs:**
```
Show the Homebridge logs here, remove any sensitive information.

[20.8.2023, 17:16:21] Parent process did not respond to port allocation request within 5 seconds - assigning random port.
Error: Accessory Bad experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (C:\Users\Max\AppData\Roaming\npm\node_modules\homebridge\src\bridgeService.ts:419:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:538:9)
    at processTimers (node:internal/timers:512:7)
[20.8.2023, 17:16:21] [homebridge-lupus-security] Child bridge process ended
[20.8.2023, 17:16:21] [homebridge-lupus-security] Process Ended. Code: 1, Signal: null
[20.8.2023, 17:16:28] [homebridge-lupus-security] Restarting Process...

```

**Plugin Config:**
```json
Show your Homebridge config.json here, remove any sensitive information.
        {
            "lupusUrl": "http://XXX.XXX.XXX.XXX",
            "lupusUsername": "XXX",
            "lupusPassword": "XXX",
            "_bridge": {
                "username": "XX:XX:XX:XX:XX:XX",
                "port": 443
            },
            "platform": "HomebridgeLupusSecurity"
        },

```

**Screenshots:**

![Screenshot 2023-08-20 171913](https://github.com/Phil0xFF/homebridge-lupus-security/assets/133262113/4c1cd424-16ff-4938-8f17-1c7da0c82a90)
![Screenshot 2023-08-20 171924](https://github.com/Phil0xFF/homebridge-lupus-security/assets/133262113/85806c82-4e56-4e0d-b8cf-3d29069d8b2e)

**Environment:**

* **Plugin Version**: 2.0.0
* **Homebridge Version**: V1.6.1
* **Node.js Version**: v18.17.1
* **NPM Version**:  Was installed on 19.08.2023 with Node.js (idk where to find the version)
* **Operating System**: Windows 10 Pro

**Comment by Phil0xFF** [comment]
Hello, does it work without using the extra "_bridge" definition?

**Comment by LEP111** [comment]
Sadly not. Homebrige isnt even starting

**Comment by LEP111** [comment]
After listing every Lupus device this error apers and the whole Hombrige restarts
```
[23.8.2023, 16:13:05] Error: Accessory Bad experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (C:\Users\Max\AppData\Roaming\npm\node_modules\homebridge\src\bridgeService.ts:419:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[23.8.2023, 16:13:05] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[23.8.2023, 16:13:10] [HB Supervisor] Restarting Homebridge...
[23.8.2023, 16:13:10] [HB Supervisor] Starting Homebridge with extra flags: -I
[23.8.2023, 16:13:10] [HB Supervisor] Started Homebridge v1.6.1 with PID: 9608
```

**Comment by LEP111** [comment]
I tried it now on my Rasberrypi with everything fresh installed and still the same error
